// Rebuild only the 155 curated artworks. Originals are never modified.
import { readFile, writeFile, mkdir, stat } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import vm from 'node:vm';
const run = promisify(execFile);
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dataPath = path.join(root, 'assets/js/data.js');
const context = { window: {} };
vm.runInNewContext(await readFile(dataPath, 'utf8'), context);
const items = context.window.ARTWORKS_DATA;
const directory = 'media/gallery';
await mkdir(path.join(root, directory), { recursive: true });
const settings = [{kind:'small',width:480,quality:80},{kind:'large',width:960,quality:80},{kind:'detail',width:0,quality:85}];
const encoder = (await run('cwebp', ['-version'])).stdout.trim();
let cursor = 0;
const manifest = new Array(items.length);
async function worker() {
  while (cursor < items.length) {
    const i = cursor++;
    const item = items[i];
    const original = item.original || (item.image.startsWith('images/') ? item.image : item.image.replace('details/', 'images/').replace(/\.webp$/, '.png'));
    const bytes = await readFile(path.join(root, original));
    const sourceHash = createHash('sha256').update(bytes).digest('hex');
    const variants = {};
    for (const setting of settings) {
      const digest = createHash('sha256').update(sourceHash+JSON.stringify(setting)+encoder+'gallery-v1').digest('hex').slice(0,16);
      const filename = `${directory}/${item.id}.${setting.kind}.${digest}.webp`;
      let existing;
      try { existing = await stat(path.join(root,filename)); } catch {}
      if (!existing?.size) {
        const args = ['-quiet','-q',String(setting.quality),'-m','4'];
        if (setting.width) args.push('-resize', String(setting.width), '0');
        await run('cwebp',[...args,path.join(root, original),'-o',path.join(root,filename)]);
      }
      variants[setting.kind] = { path:filename, bytes:(await stat(path.join(root,filename))).size };
    }
    // PNG IHDR dimensions; originals in this curated gallery are PNG files.
    if (bytes.toString('ascii',1,4)!=='PNG') throw new Error(`Expected PNG original: ${original}`);
    const width=bytes.readUInt32BE(16), height=bytes.readUInt32BE(20);
    items[i] = {id:item.id,theme:item.theme,hero:item.hero,character:item.character,thumbnail:variants.small.path,thumbnailLarge:variants.large.path,image:variants.detail.path,original,width,height};
    manifest[i] = {id:item.id,original,sourceHash,originalBytes:bytes.length,width,height,variants};
  }
}
await Promise.all(Array.from({length:4},worker));
await writeFile(dataPath,'// Generated by scripts/optimize-gallery.mjs; original assets are preserved.\nwindow.ARTWORKS_DATA = '+JSON.stringify(items,null,2)+';\n');
await writeFile(path.join(root,'scripts/gallery-assets.json'),JSON.stringify({encoder,settings,items:manifest},null,2)+'\n');
const total = key => manifest.reduce((n,x)=>n+(key==='original'?x.originalBytes:x.variants[key].bytes),0);
console.log(JSON.stringify({count:items.length,bytes:{original:total('original'),small:total('small'),large:total('large'),detail:total('detail')}},null,2));
